---
- hosts: all
  become: true
  tasks:
   - name: adding the users
     ansible.builtin.user:
      name: abhi
      password: "{{ 'password' | password_hash('sha512','mysecretsalt') }}"
      groups:
        - tcs
        - wipro
      state: "present"
      shell: "/bin/bash"
      system: false
      create_home: true
      home: "/home/abhi/"
      comment: "ansible example"
      generate_ssh_key: true  
...
