- hosts: all
  become: true
  tasks:
  - copy: src=/etc/shadow
          dest=/tmp
          owner=akash
          group=tcs
          mode=777
  - file: path=/tmp/azure
          state=directory
  - yum:  name=nfs-utils
          state=latest
  - service: name=nfs-server
             state=started
