---
- hosts: all
  become: true
  tasks:
   - copy:
      src: "{{ item[0] }}"
      dest: "{{ item[1] }}"
     with_nested:
       - [ '/home/ansible/shelll.sh','/home/ansible/removepack.yml','/home/ansible/simple1loop.yml']
       - [ '/tmp','/mnt','/opt' ]
...
