---
- hosts: all
  become: true
  tasks:
   - copy: 
      src: "{{item}}"
      dest: /tmp
     with_items:

      - /etc/group
      - /etc/passwd
      - /home/ansible/ping.yml
 
   - file:
       path: "{{item}}"
       state: directory
     with_items:
      - /tmp/akash3
      - /tmp/akash4
      - /tmp/akash5
   - copy:
       src: /etc/passwd
       dest: "{{item}}"
     with_items:
      - /tmp/akash3
      - /tmp/akash4
      - /tmp/akash5

... 
