- hosts: all
  become: yes
  tasks:
   - copy: src=/etc/group dest=/tmp owner=akash group=tcs mode=777
   - file: path=/tmp/aws state=directory
   - yum: name=tree state=latest
   - service: name=httpd state=restarted 
